name-template: "v$RESOLVED_VERSION ğŸ”®"
tag-template: "v$RESOLVED_VERSION"
categories:
    - title: "New Features ğŸš€"
      labels:
          - "feature"
          - "enhancement"
    - title: "Bug Fixes ğŸ›"
      labels:
          - "fix"
          - "bugfix"
          - "bug"
    - title: "Breaking ğŸ¤¯"
      labels:
          - "breaking"
    - title: "Maintenance ğŸ¦"
      labels:
          - "maintenance"
category-template: "### $TITLE"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'
no-changes-template: "No changes"
exclude-labels:
    - "skip-changelog"
version-resolver:
    major:
        labels:
            - "breaking"
    minor:
        labels:
            - "feature"
            - "enhancement"
    patch:
        labels:
            - "maintenance"
            - "patch"
    default: "patch"
template: |
    $CHANGES

    **Full Changelog**: https://github.com/danpacho/tailwindest/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
